version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: restore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=Restore2024!
    command: redis-server --requirepass Restore2024! --appendonly yes

volumes:
  postgres_data:
  redis_data: 