name: Build and deploy ASP.NET Core app to Azure Web App - rcruz-restore

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./API/API.csproj

      - name: Build
        run: dotnet build ./API/API.csproj --configuration Release --no-restore

      - name: Publish (self-contained)
        run: dotnet publish ./API/API.csproj --configuration Release --output ./publish --runtime win-x64 --self-contained true

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8AAF55983785411597875A5136D732AB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CE6466838BC24F7288F0A858E829FD6B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DE6998BCC5B64F4D81CEFDFE7217ABC3 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'rcruz-restore'
          slot-name: 'Production'
          package: .
